# Generated by Django 5.2.14 on 2026-06-01 15:13

from django.db import migrations


def ensure_admin_staff(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='admin').update(
        email='admin@herbarium.ru',
        first_name='admin',
        is_staff=True,
        is_superuser=True,
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_supplyrequest'),
    ]

    operations = [
        migrations.RunPython(ensure_admin_staff, migrations.RunPython.noop),
    ]
